packages:
  - apps/*
  - libs/*
  - legacy/*
  - vanilla/*

catalog:
  "@astrojs/check": 0.7.0
  "@astrojs/netlify": 5.2.1
  "@astrojs/react": 3.3.4
  "@fontsource-variable/inter": 5.1.0
  "@fontsource-variable/montserrat": 5.0.17
  "@fontsource-variable/mulish": 5.0.18
  "@fontsource-variable/noto-sans-jp": 5.0.19
  "@fontsource-variable/raleway": 5.0.19
  "@fontsource/be-vietnam-pro": 5.1.0
  "@fontsource/inter": 5.1.0
  "@fontsource/montserrat": 5.0.17
  "@fontsource/mulish": 5.0.17
  "@fontsource/noto-sans-jp": 5.0.19
  "@fontsource/poppins": 5.0.8
  "@fontsource/raleway": 5.0.18
  "@fontsource/roboto": 5.0.8
  "@fontsource/ubuntu-mono": 5.0.20
  "@hrc/button": 3.1.0
  "@hrc/input": 1.1.0
  "@hrc/material-icons": 2.3.0
  "@hrc/spinner": 0.3.2
  "@hrc/toggle-theme": 2.3.0
  "@hrc/type-utils": 1.1.2
  "@material-design-icons/font": 0.14.13
  "@types/node": 20.5.0
  "@types/react": 18.2.79
  "@types/react-dom": 18.2.25
  "@typescript-eslint/eslint-plugin": 7.12.0
  "@typescript-eslint/parser": 7.12.0
  "@vitejs/plugin-react": 4.2.0
  astro: 4.8.6
  clsx: 2.0.0
  eslint: 8.57.0
  eslint-plugin-astro: 1.2.0
  eslint-plugin-react: 7.34.2
  eslint-plugin-react-hooks: 4.6.2
  eslint-plugin-react-refresh: 0.4.7
  hygen: 6.2.11
  npkill: 0.11.3
  prettier: 3.0.1
  prettier-plugin-astro: 0.13.0
  react: 18.2.0
  react-dom: 18.2.0
  react-loading-skeleton: 3.4.0
  react-paginate: 8.2.0
  react-router-dom: 6.23.1
  sass: 1.65.0
  typescript: 5.3.2
  vite: 5.0.2
  vitest: 0.34.6
  vite-plugin-hrc-import: 1.1.0
  zod: 3.22.4
  zustand: 4.4.3
