### Success response

GET http://api.weatherapi.com/v1/current.json?q=london
  &key={{WEATHERAPI_API_KEY}} HTTP/1.1

### Error response (no key)

GET http://api.weatherapi.com/v1/current.json?q=london HTTP/1.1
